[env:esp32-c3-zero]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; ESP32-C3-Zero uses the chip's native USB connection.
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

